#### general settings
name: STEN
use_tb_logger: true
model: sr
distortion: sr
scale: 1
gpu_ids: [1]

#### datasets
datasets:
  train:
    name: UEN
    mode: UEN_train
    interval_list: [1]
    random_reverse: false
    border_mode: false
#    dataroot: /data/1760921465/dped/iphone/test_data/patches
    cache_keys: ~
    filelist: /home/jieh/Projects/ExposureFrequency/FastFourierExp1/data/groups_train_mixexposure.txt

    use_shuffle: true
    n_workers: 0  # per GPU
    batch_size: 6
    IN_size: 384
    augment: true
    color: RGB

  val:
    name: UEN
    mode: UEN_val
#    dataroot: /data/1760921465/dped/iphone/test_data/patches
    filelist: /home/jieh/Projects/ExposureFrequency/FastFourierExp1/data/groups_valid_mixexposure.txt

    batch_size: 1
    use_shuffle: false


#### network structures
network_G:
  which_model_G: Net1
  nc: 8
  groups: 8

#### path
path:
  root: /home/jieh/Projects/ExposureFrequency/FastFourierExp1/output1
  results_root: /home/jieh/Projects/ExposureFrequency/FastFourierExp1/output1
  pretrain: /home/jieh/Projects/ExposureFrequency/FastFourierExp1/pretrain1
  pretrain_model_G: /home/jieh/Projects/ExposureFrequency/FastFourierExp1/SOTA_Finals/models/0_bestavg.pth
  strict_load: false
  resume_state: ~

train:
  lr_G: 0.00007
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 120000
  ewc: False
  distill: False
  ewc_coff: 8.0
  distill_coff: 0.05
  fix_some_part: ~
  warmup_iter: -1
  ComputeImportance: False
  istraining: True
  lr_steps: [40000, 80000]
  lr_gamma: 0.5
  eta_min: 5e-06
  pixel_criterion: l1
  pixel_weight: 5000.0
  ssim_weight: 1000.0
  vgg_weight: 1000.0
  val_epoch: 1.0
  manual_seed: 0

#### logger
logger:
  print_freq: 80
  save_checkpoint_epoch: !!float 100
